sonar.projectKey=cleanarchitecture
sonar.projectName=cleanarchitecture
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.token=squ_9037802f377e031a82ed03005edeb40bf73ee783

sonar.exclusions=node_modules/**,coverage/**,.scannerwork/**,uploads/**
sonar.scm.disabled=true